// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: core_engine.proto

package core_engine

import (
	common "github.com/aRKO872/ecommerce-product-admin-microservice-utils/grpc/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_core_engine_proto protoreflect.FileDescriptor

const file_core_engine_proto_rawDesc = "" +
	"\n" +
	"\x11core_engine.proto\x12\vcore_engine\x1a\fcommon.proto2M\n" +
	"\x11CoreEngineService\x128\n" +
	"\tHeartbeat\x12\x13.common.GRPCRequest\x1a\x14.common.GRPCResponse\"\x00BPZNgithub.com/aRKO872/ecommerce-product-admin-microservice-utils/grpc/core-engineb\x06proto3"

var file_core_engine_proto_goTypes = []any{
	(*common.GRPCRequest)(nil),  // 0: common.GRPCRequest
	(*common.GRPCResponse)(nil), // 1: common.GRPCResponse
}
var file_core_engine_proto_depIdxs = []int32{
	0, // 0: core_engine.CoreEngineService.Heartbeat:input_type -> common.GRPCRequest
	1, // 1: core_engine.CoreEngineService.Heartbeat:output_type -> common.GRPCResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_core_engine_proto_init() }
func file_core_engine_proto_init() {
	if File_core_engine_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_core_engine_proto_rawDesc), len(file_core_engine_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_core_engine_proto_goTypes,
		DependencyIndexes: file_core_engine_proto_depIdxs,
	}.Build()
	File_core_engine_proto = out.File
	file_core_engine_proto_goTypes = nil
	file_core_engine_proto_depIdxs = nil
}
